name: uptime

on:
  schedule:
    - cron: 0 * * * *

  push:
    branches:
      - main
    paths:
      - ".github/workflows/uptime.yaml"
      - ".github/scripts/uptime.py"

permissions:
  contents: write

jobs:
  uptime:
    runs-on: ubuntu-latest
    environment: uptime
    steps:
      - name: Checkout
        continue-on-error: true
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip

      - name: Install dependencies
        run: pip install httpx

      - name: Create uptime.md
        run: |
          mkdir -p .github/uptime
          python .github/scripts/uptime.py .github/uptime/uptime.json docs/uptime.md

      - name: Commit and Push changes
        run: |
          git config --global user.name "[AUTO UPTIME]"
          git config --global user.email "guionardo.furlan@escoteiros.org.br"

          git add .
          git commit -m "[UPTIME] updating data"
          git push

  mkdocs:
    runs-on: ubuntu-latest
    needs: ["uptime"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
      - run: pip install mkdocs-material mkdocs-minify-plugin      
      - name: Run mkdocs
        run: mkdocs gh-deploy --force
