name: uptime

on:
  schedule:
    - cron: 0 * * * *

  push:
    branches:
      - main
    paths:
      - '.github/workflows/uptime.yaml'

      
permissions:
  contents: write
jobs:
    
  uptime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

            
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: uptime-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            uptime-
      - name: Install dependencies
        run: pip install httpx

      - name: Read previous uptime data
        continue-on-error: true
        uses: actions/download-artifact@v3     

      - name: Create uptime.md        
        run: python .github/scripts/uptime.py uptime.json docs/uptime.md

      - name: Upload uptime.json
        uses: actions/upload-artifact@v3
        with:
          name: uptime
          path: |
            uptime.json
            docs/uptime.md                    

  mkdocs:
    runs-on: ubuntu-latest
    needs: ["uptime"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material mkdocs-minify-plugin
      - name: Read uptime.md
        continue-on-error: true
        uses: actions/download-artifact@v3
        with:
            path: docs 
      - run: mkdocs gh-deploy --force
