name: uptime

on:
  schedule:
    - cron: 0 * * * *

  push:
    branches:
      - main
    paths:
      - '.github/workflows/uptime.yaml'

      
permissions:
  contents: write
jobs:
    
  uptime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
                  
      - name: Install dependencies
        run: pip install httpx

      - name: Read previous uptime data
        continue-on-error: true
        uses: actions/download-artifact@v3     

      - name: Create uptime.md        
        run: python .github/scripts/uptime.py uptime.json uptime.md

      - name: Upload uptime.json and uptime.md
        uses: actions/upload-artifact@v3
        with:
          name: uptime
          path: |
            uptime.json
            uptime.md

  mkdocs:
    runs-on: ubuntu-latest
    needs: ["uptime"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      - run: pip install mkdocs-material mkdocs-minify-plugin
      - name: Read uptime.md
        continue-on-error: true
        uses: actions/download-artifact@v3
      - name: Copy uptime.md
        run: cp uptime.md docs/uptime.md
      - name: Run mkdocs
        run: mkdocs gh-deploy --force
